### ISSUE TITLE
Is there an example for Linux with DBUS

### ISSUE THREAD

**Issue by genofire** [UnifiedPush/whishlist#13]
It would be nice, to have a reference Application to develop new solutions like XMPP without developing a solution for Android.

**Comment by karmanyaahm** [comment]
Do you mean a distributor? If so there's <https://github.com/UnifiedPush/gotify-dbus-rust>; and I've been working on this in Go, but it's (very) incomplete <https://github.com/karmanyaahm/np2p_linux>.

**Comment by genofire** [comment]
Nice your go implemented, not seen yet.

No I mean an application, to test your distributor like this App for android equal for dbus:

https://github.com/UnifiedPush/android-example

**Comment by karmanyaahm** [comment]
Some of those can be found here <https://github.com/UnifiedPush/go_dbus_connector/tree/main/_examples>.

**Comment by genofire** [comment]
I believe i will close this Issue after few tests

**Comment by genofire** [comment]
Nice the example looks like working (with PR) - but i do not get any distributer working.

Still on verifing if example really works.

**Comment by genofire** [comment]
I got it running with https://github.com/UnifiedPush/gotify-dbus-rust/pull/5 :)
