### ISSUE TITLE
Element Android

### ISSUE THREAD

**Issue by p1gp1g** [UnifiedPush/whishlist#4]
cf. https://github.com/vector-im/element-android/pull/3448 and https://github.com/SchildiChat/SchildiChat-android/issues/68

**Comment by genofire** [comment]
SchildChat supports UnifiedPush, now. Maybe lets rename this issue to Element (only).

**Comment by p1gp1g** [comment]
https://github.com/vector-im/element-android/pull/6228

**Comment by genofire** [comment]
I could not wait for next Release ;)
